### ISSUE TITLE
Выложить сервис на Heroku или Vercel

### ISSUE THREAD

**Issue by toplenboren** [urfu-2020/team-8#1]
## Что нужно сделать?
* [Докеризовать](https://urfu-2020.github.io/slides/second-semester/03-operating/#/65) приложение __(* опционально, возможно не понадобится)__
* Выбрать что использовать — [Heroku](https://heroku.com) или [Vercel](https://vercel.com/)
* Выложить сервис в облако, дать всем тиммейтам доступы
* Сконфигурировать приложение так, чтобы статика лежала на [surge.sh](surge.sh) [Туториал](https://urfu-2020.github.io/slides/second-semester/03-operating/#/55)
* Настроить CD — при каждом изменении `master`-ветки обновлять сервис в облаке. Можно использовать `github-actions`  но вроде советуют Travis-CI

## Что хочется видеть в итоге?
* На каком-то домене лежит наш проект
* Все тиммейты имеют доступы к облаку с приложением
* Статика приложения лежит на `surge.sh`
* На каждый `pull-request` в ветку `master` запускаются скрипты, которые проверяют — собирается ли сервис? Не сломается ли прод?
* На каждый `merge` в ветку `master` запускается скрипты, которые обновляют сервис в облаке

**Comment by Lenikas** [comment]
**Что сделал**
```
1. проект лежит на домене - https://messenger-ufru-course.herokuapp.com/
2. тиммейты пока не особо рвутся иметь доступ
3. статическая страничка проблая лежит на http://messenger.ufru.surge.sh/
4. на каждый слитый реквест в мастер просто едет новая версия,с этим буду разбираться дальше,
пока просто непрерывно катимся,тестируя на проде,как говорится
5. как сказал выше,на каждый мердж в мастер деплоим в прод
```

**Что надо сделать**

```
1. проверка на "собирается ли сервис"
2. разобраться с тем, как настроить прогон тестов до деплоя, погрузится побольше в возможности heroku
```

**Comment by toplenboren** [comment]
> **Что сделал**
> 
> ```
> 1. проект лежит на домене - https://messenger-ufru-course.herokuapp.com/
> 2. тиммейты пока не особо рвутся иметь доступ
> 3. статическая страничка проблая лежит на http://messenger.ufru.surge.sh/
> 4. на каждый слитый реквест в мастер просто едет новая версия,с этим буду разбираться дальше,
> пока просто непрерывно катимся,тестируя на проде,как говорится
> 5. как сказал выше,на каждый мердж в мастер деплоим в прод
> ```
> 
> **Что надо сделать**
> 
> ```
> 1. проверка на "собирается ли сервис"
> 2. разобраться с тем, как настроить прогон тестов до деплоя, погрузится побольше в возможности heroku
> ```

Проверка на собирается ли сервис уже сделана (если собирается тайпскрипт, значит собирается и сервис) и тесты тоже 

Проверка на сборку и тесты запускаются на пулл-реквесте. В идеале код, который не собирается вообще не должен попасть в `master` и, соответственно триггернуть деплой у Хероку

**Comment by toplenboren** [comment]
Я не увидел деплой в `surge`, было бы неплохо иметь `npm` скрипт, который при вызовые его идет и деплоит статику на `surge`
